### ISSUE TITLE
Mac os catalina don't showing anything in screenshot

### ISSUE THREAD

**Issue by hosseinmd** [bencevans/screenshot-desktop#215] opened 2021-07-26 15:18 UTC
**Describe the bug**
Screenshot in mac is just wallpaper 

**To Reproduce**

**Expected behavior**
Screenshot don't include apps in desktop and just showing wallpaper, I run screen capture from terminal and that give me same result, what is wrong in mac.

**Screenshots**
![demo](https://user-images.githubusercontent.com/45505767/127013289-4424ad17-4a32-49fe-9c1a-51edb6be9b66.png)

**Environment (please complete the following information):**
 - OS: [MacOS 10.15.7]
 - Engine [Electron]
 - Version [e.g. 12.0.3]

**Comment by bencevans** [comment] 2021-07-26 15:36
Thanks for your report @hosseinmd. I think this is a duplicate of #156 and is due to macOS permissions. Could you try the solution in https://github.com/bencevans/screenshot-desktop/issues/156#issuecomment-583008800 and report back?

**Comment by bencevans** [comment] 2021-08-05 12:23
Closing as I'm pretty sure this is a duplicate. Please feel free to reopen for discussion if you think otherwise.

**Closed by bencevans** 2021-08-05 12:23 UTC
Labels: bug
