### ISSUE TITLE
screenCapture process not closing on Windows 11

### ISSUE THREAD

**Issue by onikienko** [bencevans/screenshot-desktop#226] opened 2021-11-23 16:06 UTC
**Describe the bug**
Promise returned from `screenshot(options)` will be never resolved or rejected. Process `screenCapture_1.3.2` won't be closed.

**To Reproduce**
1. Run `npm test` on Windows 11

**Environment (please complete the following information):**
 - OS:  Window 11
 - Engines [Node v16.13.0, npm v8.1.0]

**Additional context**
The interesting things:
1. Screenshot, in fact, is taken. I'm able to find it in the Temp folder. 
2. The process `screenCapture_1.3.2` won't be closed. I have a lot of the after running tests a few times:

![image](https://user-images.githubusercontent.com/3234928/143060015-3f2be6ac-27b8-483b-97c0-c820dd389e47.png)

**Comment by bencevans** [comment] 2021-12-06 21:35
Hi @onikienko,

Thanks for reporting. I'm struggling to replicate the issue. I'm a little bit limited as I only have an ARM Windows 11 Insider Build at my disposal. I don't suppose you've done any further debugging?

Please could you share the exact dependency tree / package-lock.json if it differs from what's in the repository?

**Comment by onikienko** [comment] 2021-12-08 12:10
Hi @bencevans 

package-lock.json is the same as in the repo. The only difference is this "funding" prop. I don't think it may break things :)

![image](https://user-images.githubusercontent.com/3234928/145205170-ebceecf5-06b1-4b34-8909-fc05e7e277b7.png)

For debug. I was only able to realize that this callback https://github.com/bencevans/screenshot-desktop/blob/d9ea0db0b16c2f0c002131d9dde761a52d300691/lib/win32/index.js#L26 will never be executed. But a screenshot is taken. I have no idea how to debug further.

**Comment by gazhay** [comment] 2022-05-04 11:14
I couldn't reproduce this just now, worked fine for me on windows 11.

**Comment by bencevans** [comment] 2022-05-04 12:39
Thanks for checking @gazhay. I shall close this issue for now. If anyone's able to reproduce/ @onikienko you are still experiencing this issue and have any further information you can share to assist us in reproducing please feel free to reopen.

**Closed by bencevans** 2022-05-04 12:39 UTC
Labels: bug
