### ISSUE TITLE
Windows 10 Application Error

### ISSUE THREAD

**Issue by dovk** [bencevans/screenshot-desktop#144] opened 2019-07-24 19:35 UTC
I have used `screenshot-desktop` on Windows7 without any problems, and yesterday when I installed it on Windows10, I got the following message :
![image](https://user-images.githubusercontent.com/26749318/61822573-8604cb80-ae62-11e9-950e-d7ef17628490.png)
I can continue to work but the message keeps popping up. 
I tried it on a Windows 2016 server whose desktop is related to Windows10 and it was OK.
Any ideas ?

**Comment by bencevans** [comment] 2019-07-25 10:47
You could try recompiling `lib/win32/screenCapture_1.3.2.exe` by deleting it and running `lib/win32/screenCapture_1.3.2.bat` in the same directory on the machine your having issues. A bit of a guess / investigation but see if that fixes it.

**Comment by dovk** [comment] 2019-07-25 18:50
Thanks, I'll check it out

**Comment by bencevans** [comment] 2021-06-02 14:27
Hi @dovk, did you manage to resolve this? I'm still unable to reproduce.

**Comment by dovk** [comment] 2021-06-02 20:06
Sorry, it's been quite a while. The project folded so I didn't continue with it. All the best!

**Comment by bencevans** [comment] 2021-06-02 20:51
No worries, thanks for getting back anyway! Shall close this as there doesn't appear to be anyone else running in to it.

**Closed by bencevans** 2021-06-02 20:51 UTC
